/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.prueba;

import javax.swing.JOptionPane;

/**
 *
 * @author Windows
 */
public class PANTALLA extends javax.swing.JFrame {

    /**
     * Creates new form PANTALLA
     */
    public PANTALLA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JPanel();
        bks = new javax.swing.JPanel();
        campo6 = new javax.swing.JTextField();
        moneda6 = new javax.swing.JLabel();
        bandera6 = new javax.swing.JLabel();
        bka = new javax.swing.JPanel();
        campo1 = new javax.swing.JTextField();
        moneda1 = new javax.swing.JLabel();
        bandera1 = new javax.swing.JLabel();
        campo2 = new javax.swing.JTextField();
        campo3 = new javax.swing.JTextField();
        campo4 = new javax.swing.JTextField();
        campo5 = new javax.swing.JTextField();
        moneda2 = new javax.swing.JLabel();
        moneda3 = new javax.swing.JLabel();
        moneda4 = new javax.swing.JLabel();
        moneda5 = new javax.swing.JLabel();
        bandera2 = new javax.swing.JLabel();
        bandera3 = new javax.swing.JLabel();
        bandera4 = new javax.swing.JLabel();
        bandera5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        back.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bks.setBackground(new java.awt.Color(153, 0, 153));

        campo6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        campo6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        campo6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        campo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo6ActionPerformed(evt);
            }
        });

        moneda6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        moneda6.setText("$");

        bandera6.setIcon(
                new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/prueba/BANDERAS/COLOMBIA.png"))); // NOI18N

        javax.swing.GroupLayout bksLayout = new javax.swing.GroupLayout(bks);
        bks.setLayout(bksLayout);
        bksLayout.setHorizontalGroup(
                bksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bksLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(bandera6)
                                .addGap(18, 18, 18)
                                .addComponent(moneda6)
                                .addGap(18, 18, 18)
                                .addComponent(campo6, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(46, Short.MAX_VALUE)));
        bksLayout.setVerticalGroup(
                bksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bksLayout.createSequentialGroup()
                                .addContainerGap(37, Short.MAX_VALUE)
                                .addGroup(bksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(bandera6, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(bksLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(campo6, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(moneda6, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(27, 27, 27)));

        back.add(bks, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 100));

        bka.setBackground(new java.awt.Color(0, 153, 153));
        bka.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        campo1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        campo1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        campo1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        moneda1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        moneda1.setText("$");

        bandera1.setIcon(
                new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/prueba/BANDERAS/ESTADOS UNIDOS.jpg"))); // NOI18N

        campo2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        campo2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        campo2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        campo3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        campo3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        campo3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        campo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo3ActionPerformed(evt);
            }
        });

        campo4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        campo4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        campo4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        campo5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        campo5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        campo5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        moneda2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        moneda2.setText("€");

        moneda3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        moneda3.setText("£");

        moneda4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        moneda4.setText("¥");

        moneda5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        moneda5.setText("¥");

        bandera2.setIcon(
                new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/prueba/BANDERAS/UNION EUROPEA.jpg"))); // NOI18N

        bandera3.setIcon(
                new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/prueba/BANDERAS/INGLATERRA.jpg"))); // NOI18N

        bandera4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/prueba/BANDERAS/JAPON.jpg"))); // NOI18N

        bandera5.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/com/mycompany/prueba/BANDERAS/REPUBLICA POPULAR DE CHINA.jpg"))); // NOI18N

        javax.swing.GroupLayout bkaLayout = new javax.swing.GroupLayout(bka);
        bka.setLayout(bkaLayout);
        bkaLayout.setHorizontalGroup(
                bkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(bkaLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(bkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(bkaLayout.createSequentialGroup()
                                                .addComponent(bandera4)
                                                .addGap(18, 18, 18)
                                                .addComponent(moneda4)
                                                .addGap(18, 18, 18)
                                                .addComponent(campo2, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(bkaLayout.createSequentialGroup()
                                                .addComponent(bandera2)
                                                .addGap(18, 18, 18)
                                                .addComponent(moneda2)
                                                .addGap(18, 18, 18)
                                                .addComponent(campo3, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(bkaLayout.createSequentialGroup()
                                                .addComponent(bandera3)
                                                .addGap(18, 18, 18)
                                                .addComponent(moneda3)
                                                .addGap(18, 18, 18)
                                                .addComponent(campo4, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(bkaLayout.createSequentialGroup()
                                                .addComponent(bandera5)
                                                .addGap(18, 18, 18)
                                                .addComponent(moneda5)
                                                .addGap(18, 18, 18)
                                                .addComponent(campo5, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(bkaLayout.createSequentialGroup()
                                                .addComponent(bandera1)
                                                .addGap(18, 18, 18)
                                                .addComponent(moneda1)
                                                .addGap(18, 18, 18)
                                                .addComponent(campo1, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(45, Short.MAX_VALUE)));
        bkaLayout.setVerticalGroup(
                bkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(bkaLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(bkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(campo1, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(moneda1, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bandera1, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(bkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(campo3, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(moneda2, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bandera2, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(bkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(campo4, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(moneda3, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bandera3, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(bkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(campo2, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(moneda4, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bandera4, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(bkaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(campo5, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(moneda5, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bandera5, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(29, Short.MAX_VALUE)));

        back.add(bka, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 350, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 350,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(back, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campo3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_campo3ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_campo3ActionPerformed

    private void campo6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_campo6ActionPerformed
        // TODO add your handling code here:
        // Get the value from the text field
        String value = campo6.getText();

        // Only work with numbers
        if (value.matches("\\d+")) {

            double number = Double.parseDouble(value);

            PRUEBA d = new PRUEBA();
            double dolar = d.dolar(number);
            double euro = d.dolar(number);
            double libra = d.dolar(number);
            double japon = d.dolar(number);
            double china = d.dolar(number);

            campo1.setText(String.valueOf(dolar) + " DOLARES");
            campo2.setText(String.valueOf(euro) + " EUROS");
            campo3.setText(String.valueOf(libra) + " LIBRAS");
            campo4.setText(String.valueOf(japon) + " YENES");
            campo5.setText(String.valueOf(china) + " YUANES");

        } else {

            JOptionPane.showMessageDialog(null, "EL VALOR NO ES UN NÚMERO");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PANTALLA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PANTALLA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PANTALLA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PANTALLA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PANTALLA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel back;
    private javax.swing.JLabel bandera1;
    private javax.swing.JLabel bandera2;
    private javax.swing.JLabel bandera3;
    private javax.swing.JLabel bandera4;
    private javax.swing.JLabel bandera5;
    private javax.swing.JLabel bandera6;
    private javax.swing.JPanel bka;
    private javax.swing.JPanel bks;
    private javax.swing.JTextField campo1;
    private javax.swing.JTextField campo2;
    private javax.swing.JTextField campo3;
    private javax.swing.JTextField campo4;
    private javax.swing.JTextField campo5;
    private javax.swing.JTextField campo6;
    private javax.swing.JLabel moneda1;
    private javax.swing.JLabel moneda2;
    private javax.swing.JLabel moneda3;
    private javax.swing.JLabel moneda4;
    private javax.swing.JLabel moneda5;
    private javax.swing.JLabel moneda6;
    // End of variables declaration//GEN-END:variables
}
